---
title: "quiz2"
author: "Collin"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#for calculating areas to the right of a standardized critical value (normal distribution)
1 - pnorm(.9759)


1- pnorm(.732064)

1 - pnorm(2.5)


pnorm(1.645,lower.tail = FALSE)
2*pnorm(1.645,lower.tail = FALSE)

2*pnorm(1.96, lower.tail = FALSE)
pnorm(2.5, lower.tail = FALSE)



pnorm(4.41,lower.tail = FALSE)
```

```{r}
#binomial probabilities

1 - pbinom(7,20,.3)

pbinom(25,36,.5,lower.tail = FALSE)

dbinom(2,20,.25)

1 - pbinom(20,30,.4)

1 - pnorm(2.79509)

dbinom(3,3,.5)

pchisq(23.36,3,lower.tail = FALSE)



```


```{r}
#likelihood ratio test and chi square
pchisq(2.971,1,lower.tail = FALSE)


#Likelihood ratio function: calculates likelihood ratio statistic in the binomial case
likelihoodRatio <- function(pnot,obs,n) {
phat = obs/n
return((2*(obs)*log(phat/pnot) + 2*(n - obs)*log((1-phat)/(1-pnot))))
}
likelihoodRatio(.2,17,150)

#likelihood ratio statistic calculator in the multinomial case
likelihoodRatio2 = function(vecOfObs,vecOfExp){
  returnLikelihoodRatio = 0
  if (length(vecOfObs) != length(vecOfExp)){
    stop("vectors must be of equal length")
  }
  else{
    for(i in 1:length(vecOfObs)){
      returnLikelihoodRatio = returnLikelihoodRatio + vecOfObs[i]*log(vecOfObs[i]/vecOfExp[i])
    }
    return(2*returnLikelihoodRatio)
  }
}





#calculates the ChiSquare statistic
chiStatistic = function(vecOfObs,vecOfExpected){
  returnChisq = 0
  if (length(vecOfObs) != length(vecOfExpected)){
    stop("vectors must be of equal length")
  }
  else{
    for(i in 1:length(vecOfObs)){
      returnChisq = returnChisq + ((vecOfObs[i] - vecOfExpected[i])^2/vecOfExpected[i])
    }
    return(returnChisq)
  }
}



vecOfObs = c(873,873,304,41)
vecOfExp = c(982.8,763.197,982.8,763.197)

chiStatistic(vecOfObs,vecOfExp)
likelihoodRatio2(vecOfObs,vecOfExp)





pchisq(23.36,3,lower.tail = FALSE)
qchisq(.05,3,lower.tail = FALSE) #critical value for Chi Square distribution with 2 degrees of freedom



likelihoodRatio(.2,17,150)


```





Confidence Interval for odds ratio
```{r}


#default 95% Confidence interval
oddsRatioCI <- function(oddsRatio, counts, confidence = .95){
  val = (1-confidence)/2
  critical_value = abs(qnorm(val))
  
  standardError = (sum(1/counts))^(1/2) #triple and quadruple check this
  lowerBound = log(oddsRatio) - critical_value*standardError
  upperBound = log(oddsRatio) + critical_value*standardError
  df = data.frame(lowerBound = exp(lowerBound), upperBound = exp(upperBound))
  return(df)
 
}

#test
oddsRatio = 3.08
counts = c(42,18,28,37)

oddsRatioCI(oddsRatio = oddsRatio, counts = counts)





```


Test for Independence
```{r}

matrix = matrix(c(873,304,873,41),nrow = 2, ncol = 2)



chisq.test(matrix)

library(tidyverse)
3 %>% choose(2)

```


```{r}
#Problem 1

#Response small or large
#placebo or vaccine
n11=335
n12=76
n21=302
n22=105

nObs=rbind(c(n11,n12),c(n21,n22))
nObs
n=sum(nObs)
#Test if the subject response (small or large) is independent of having vaccine
colSums(nObs)
rowSums(nObs)

#Expected counts under the null hypothesis of independence
u11=rowSums(nObs)[1]*colSums(nObs)[1]/n
u12=rowSums(nObs)[1]*colSums(nObs)[2]/n
u21=rowSums(nObs)[2]*colSums(nObs)[1]/n
u22=rowSums(nObs)[2]*colSums(nObs)[2]/n
uExpected=rbind(c(u11,u12),c(u21,u22))

uExpected

#Pearson's chi-squared statistic

(nObs-uExpected)^2/uExpected
Xp=sum((nObs-uExpected)^2/uExpected)

1-pchisq(Xp,df=(2-1)*(2-1)) #reject the null H0 that response is independent of vaccine

#Likelihood ratio statistic
LR=2*sum(log(nObs/uExpected)*nObs)

log(n11/u11)*n11 #compare entries against log(nObs/uExpected)*nObs
log(n21/u21)*n21

1-pchisq(LR,df=(2-1)*(2-1)) #reject the null H0 that response is independent of vaccine

#there are two more approaches for a 2x2 contingency table
pi1=nObs[1,1]/rowSums(nObs)[1]
pi2=nObs[2,1]/rowSums(nObs)[2]

SE=sqrt(pi1*(1-pi1)/rowSums(nObs)[1]+pi2*(1-pi2)/rowSums(nObs)[2])
z=(pi1-pi2)/SE
qnorm(1-0.05/2)
abs(z) #reject H0 since |z|>1.96   (here assume alpha is 0.05)

#p-value
2*(1-pnorm(abs(z)))

#Problem 2

nObs=rbind(c(500,32),c(6124,93344))

#Multinomial sampling or independent multinomials?

#Estimated probability of testing positive
n=sum(nObs)
colSums(nObs)[1]/n

#Estimated probability of having the disease
rowSums(nObs)[1]/n

#Sensitivity is P(test positive given subject has the disease)
#Estimate
nObs[1,1]/rowSums(nObs)[1]

#Specificity is P(test negative given that subject doesn't have disease)
nObs[2,2]/rowSums(nObs)[2]

#false positive (doesn't have disease given that the test is positive)
nObs[2,1]/colSums(nObs)[1]

#false negative (having the disease given that the test is negative)
nObs[1,2]/colSums(nObs)[2]




################
pDisease=0.001
sens=0.95
spec=0.94
sens*pDisease/(sens*pDisease+(1-spec)*(1-pDisease))

pDisease=0.15
sens*pDisease/(sens*pDisease+(1-spec)*(1-pDisease))



```

Standardized Residual Calculator
```{r}
r = matrix(c(873,304,441,80,873,41), nrow = 2, ncol = 3, byrow = FALSE)


#b) standardized residuals


for(i in 1:2){
  for(j in 1:2){
    r[i,j]=(nObs[i,j]-expected[i,j])/sqrt(expected[i,j]*(1-rSums[i]/n)*(1-cSums[j]/n))
  }
}
r
```



EXPECTED COUNT CALCULATOR
```{r}

#Problem 1
nObs=rbind(c(873,441,873),c(304,80,41)) #matrix of observed counts
rSums=rowSums(nObs)
cSums=colSums(nObs)
n=sum(nObs)

#muij= ni+  n+j /n

#a) TO GET EXPECTED COUNTS FOR TEST OF INDEPENDENCE
expected=rSums%*%t(cSums)/n
rSums[2]*cSums[1]/n
expected










```

```{r}
#Poisson
#lambda = 6, P(Y=6)
dpois(6,6)


#lambda = 6, P(Y>=3)
1 - ppois(2,6)

?qbinom

```

